-- PostgreSQL veritabanı yedeği (Düzeltilmiş Versiyon)

-- 1. AYARLAR (Standart PostgreSQL Ayarları)
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- --------------------------------------------------------
-- 2. TABLO: BOOKS (Kitaplar)
-- --------------------------------------------------------

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255),
    image text,
    owner character varying(255),
    status character varying(255),
    title character varying(255)
);

-- Books tablosu için ID otomatik artış ayarı (Sequence)
ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- --------------------------------------------------------
-- 3. TABLO: USERS (Kullanıcılar)
-- --------------------------------------------------------

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar character varying(255),
    email character varying(255),
    full_name character varying(255),
    password character varying(255),
    trust_score integer NOT NULL,
    username character varying(255),
    about_me character varying(255),
    current_status character varying(255),
    location character varying(255),
    phone character varying(255),
    profile_image text
);

-- Users tablosu için ID otomatik artış ayarı (Sequence)
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- --------------------------------------------------------
-- 4. PRIMARY KEY (Birincil Anahtarlar)
-- --------------------------------------------------------
-- Tabloların performanslı çalışması için ID'leri birincil anahtar yapıyoruz.

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- --------------------------------------------------------
-- 5. ÖRNEK VERİ YÜKLEMESİ
-- --------------------------------------------------------
-- Not: Dosyanızdaki veri kısmı bozuk olduğu için, "COPY" komutu yerine
-- daha güvenli olan "INSERT" komutu ile kurtarılan ilk veriyi ekledim.
-- Resim verisi çok uzun olduğu için kısaltılmıştır, sisteminizde güncelleyebilirsiniz.

INSERT INTO public.books (id, author, image, owner, status, title)
VALUES (1, 'Michael Part', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...', 'mert61', 'available', 'Benim Adım Messi');

-- İşlem tamamlandığında otomatik olarak ID sayacını günceller
SELECT setval('public.books_id_seq', (SELECT MAX(id) FROM public.books));